name: Update data

on:
    # schedule:
    #     - cron: 0 0 1 * *
    workflow_dispatch:
    push:
      branches:
        - feat/auto-data-update

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      # This is needed because we want to write back the data to github
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # Other steps that change files in the repository
      - name: Run the data download script
        run: ./download.sh

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Commit all changed files back to the repository
      - name: Commit changes to a new branch
        id: commit-changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Update data
            create_branch: true
            branch: update-data-${{ env.NOW }}
            file_pattern: 'flask/**.txt surface-pfp/*.txt'

      - name: Create pull request to main
        if: steps.commit-changes.outputs.changes_detected == 'true'
        run: gh pr create -H update-data-${{ env.NOW }} -B main --title 'Update data ${{ env.NOW }}' --body 'Scheduled data update. cc @slesaad \n Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
